name: The Map Academy
description: Learn to create maps on the web and visualize geospatial data
baseurl: 'http://cartodb.github.io/academy'
cartodburl: 'http://cartodb.com'
permalink: /:title.html
analytics_property_id: UA-20934186-3
mixpanel_token: 9b1d8a4fb14fa98d50615108b8b0161a
highlighter: 'pygments'
encoding: utf-8